<?xml version="1.0" encoding="UTF-8" ?>
<testsuites errors="0"
            failures="1"
            tests="3">

  <testsuite name="lab_5"
    errors="0" failures="1" hostname="" id="" package="lab_5" skipped="1"
    tests="3" time="10.97" timestamp="Sun, 24 Apr 2016 15:38:13 GMT">
  
    <testcase name="Hello Test!" time="6.118" assertions="7">

    

    

    

    

    

    

    
    </testcase>
  
    <testcase name="Incident From Test" time="4.849" assertions="4">

    

    

      <failure message="Expected element &lt;//select[@id=&#39;incident\.subcategory&#39;]/option[text()=&#39;Email&#39;]&gt; to be present - element was not found">    at Object.module.exports.Incident From Test (/Users/dave.slusher/Box Sync/Dave Slusher/K16/Git/cc16_automated_testing_workshop_samples/Lab_5/nightwatch/tests/lab_5.js:27:21)
    at Module.call (/usr/local/lib/node_modules/nightwatch/lib/runner/module.js:63:34)
    at /usr/local/lib/node_modules/nightwatch/lib/runner/testcase.js:97:29
    at _fulfilled (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:125:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)</failure>

    
    </testcase>
  
  
    
    <testcase
      name="QUnit">
      <skipped />
    </testcase>
    
  
  </testsuite>
</testsuites>
